version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: sukablyat007/ecommerce-server:latest
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - '5000:5000'
        command: npm start
        environment:
            - NODE_ENV=development
        depends_on:
            - db

    db:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
