version: '3.8'

services:
    app:
        image: node:20.13
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - '3000:3000'
        command: npm start
        environment:
            - NODE_ENV=development
        depends_on:
            - db

    db:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
